### ISSUE TITLE
Making SwipeListView Works With Custom ListView with JSON Parsing.

### ISSUE THREAD

**Issue by Mounir-Hafsa** [yuqirong/SwipeListView#1]
Hello Sir , 
Im asking for your help to Implement this code and make it work on CustomListView With Json Parsing ! 
Thank you .

**Comment by yuqirong** [comment]
Hi,guy!
What's wrong with your codes.

**Comment by Mounir-Hafsa** [comment]
So im Trying to Make your Code work with a Custom listView and to Show Images and Text From Database using JSOn , but i found myself stuck and can't undrestand how to make it work !

**Comment by yuqirong** [comment]
have any error message? you can show it to me.
Maybe if your project is unimportant,you can send your project to me!!

**Comment by Mounir-Hafsa** [comment]
i already Sent a Mail to you , we'll talk there , and i will explain everything , Thanks a Million for everything !

**Comment by Mounir-Hafsa** [comment]
Hello

2016-03-11 3:47 GMT+01:00 俞其荣 <notifications@github.com>:
